INSERT INTO Composant VALUES (1, 'Viande', 'Blanc de Poulet', NULL);
INSERT INTO Composant VALUES (2, 'Viande', 'Bœuf haché', NULL);
INSERT INTO Composant VALUES (3, 'Laitier', 'Crème fraîche', 'Lactose');
INSERT INTO Composant VALUES (4, 'Laitier', 'Beurre doux', 'Lactose');
INSERT INTO Composant VALUES (5, 'Laitier', 'Fromage râpé', 'Lactose');
INSERT INTO Composant VALUES (6, 'Céréale', 'Farine de Blé', 'Gluten');
INSERT INTO Composant VALUES (7, 'Céréale', 'Pâtes', 'Gluten');
INSERT INTO Composant VALUES (8, 'Céréale', 'Riz basmati', NULL);
INSERT INTO Composant VALUES (9, 'Légume', 'Carotte', NULL);
INSERT INTO Composant VALUES (10, 'Légume', 'Oignon', NULL);
INSERT INTO Composant VALUES (11, 'Légume', 'Tomate', NULL);
INSERT INTO Composant VALUES (12, 'Fruit à coque', 'Amande effilée', 'Fruits à coque');
INSERT INTO Composant VALUES (13, 'Fruit à coque', 'Noix de pécan', 'Fruits à coque');
INSERT INTO Composant VALUES (14, 'Fruit à coque', 'Cacahuète', 'Arachide');
INSERT INTO Composant VALUES (15, 'Poisson', 'Pavé de Saumon', 'Poisson');
INSERT INTO Composant VALUES (16, 'Poisson', 'Cabillaud', 'Poisson');
INSERT INTO Composant VALUES (17, 'Crustacé', 'Crevette rose', 'Crustacés');
INSERT INTO Composant VALUES (18, 'Épice', 'Poivre Noir', NULL);
INSERT INTO Composant VALUES (19, 'Épice', 'Curry en poudre', NULL);
INSERT INTO Composant VALUES (20, 'Condiment', 'Moutarde de Dijon', 'Moutarde');
INSERT INTO Composant VALUES (21, 'Condiment', 'Sauce Soja', 'Soja et Gluten');
INSERT INTO Composant VALUES (22, 'Œuf', 'Œuf entier', 'Œuf');
INSERT INTO Composant VALUES (23, 'Légumineuse', 'Lentilles corail', NULL);
INSERT INTO Composant VALUES (24, 'Légumineuse', 'Pois chiches', NULL);
INSERT INTO Composant VALUES (25, 'Matière grasse', 'Huile d''olive', NULL);
INSERT INTO Composant VALUES (26, 'Matière grasse', 'Huile de sésame', 'Sésame');
INSERT INTO Composant VALUES (27, 'Herbe', 'Basilic frais', NULL);
INSERT INTO Composant VALUES (28, 'Herbe', 'Ciboulette', NULL);
INSERT INTO Composant VALUES (29, 'Sucrerie', 'Chocolat noir', 'Traces de fruits à coque');
INSERT INTO Composant VALUES (30, 'Sucrerie', 'Miel', NULL);
