INSERT INTO Légume VALUES (1, 1, 'Onion');
INSERT INTO Légume VALUES (2, 1, 'Jerusalem Artichoke');
INSERT INTO Légume VALUES (3, 0, 'Radish');
INSERT INTO Légume VALUES (4, 0, 'Raspberry');
INSERT INTO Légume VALUES (5, 1, 'Arugula');
INSERT INTO Légume VALUES (6, 1, 'Sweet Potato');
INSERT INTO Légume VALUES (7, 0, 'Peas');
INSERT INTO Légume VALUES (8, 1, 'Green Pepper');
INSERT INTO Légume VALUES (9, 1, 'Zucchini');
INSERT INTO Légume VALUES (10, 1, 'Leeks');
INSERT INTO Légume VALUES (11, 0, 'Carob Carrot');
INSERT INTO Légume VALUES (12, 1, 'Brussels Sprouts');
INSERT INTO Légume VALUES (13, 1, 'Broccoli');
INSERT INTO Légume VALUES (14, 1, 'Green Pepper');
INSERT INTO Légume VALUES (15, 0, 'Asian Greens');
INSERT INTO Légume VALUES (16, 0, 'Cabbage');
INSERT INTO Légume VALUES (17, 0, 'Pumpkin');
INSERT INTO Légume VALUES (18, 0, 'Carrot');
INSERT INTO Légume VALUES (19, 0, 'Artichoke');
