INSERT INTO Légume VALUES (1, 0, 'Eggplant');
INSERT INTO Légume VALUES (2, 1, 'Lettuce');
INSERT INTO Légume VALUES (3, 0, 'English Spinach');
INSERT INTO Légume VALUES (4, 1, 'Lettuce');
INSERT INTO Légume VALUES (5, 1, 'Cauliflower');
INSERT INTO Légume VALUES (6, 0, 'Broccoli');
INSERT INTO Légume VALUES (7, 1, 'Arugula');
INSERT INTO Légume VALUES (8, 1, 'Carob Carrot');
INSERT INTO Légume VALUES (9, 1, 'Eggplant');
INSERT INTO Légume VALUES (10, 1, 'Bean Sprouts');
INSERT INTO Légume VALUES (11, 1, 'Raspberry');
INSERT INTO Légume VALUES (12, 0, 'Radicchio');
INSERT INTO Légume VALUES (13, 1, 'Chinese Cabbage');
INSERT INTO Légume VALUES (14, 1, 'Jerusalem Artichoke');
INSERT INTO Légume VALUES (15, 0, 'Fresh Chillies');
INSERT INTO Légume VALUES (16, 0, 'Endive');
INSERT INTO Légume VALUES (17, 1, 'Cauliflower');
INSERT INTO Légume VALUES (18, 1, 'English Spinach');
INSERT INTO Légume VALUES (19, 1, 'Cucumber');
