INSERT INTO Légume VALUES (1, 1, 'Cos lettuce');
INSERT INTO Légume VALUES (2, 1, 'Pumpkin');
INSERT INTO Légume VALUES (3, 0, 'Squash');
INSERT INTO Légume VALUES (4, 0, 'Okra');
INSERT INTO Légume VALUES (5, 0, 'Pumpkin');
INSERT INTO Légume VALUES (6, 1, 'Beetroot');
INSERT INTO Légume VALUES (7, 1, 'Bean Sprouts');
INSERT INTO Légume VALUES (8, 1, 'Zucchini');
INSERT INTO Légume VALUES (9, 0, 'Leeks');
INSERT INTO Légume VALUES (10, 0, 'Green beans');
INSERT INTO Légume VALUES (11, 1, 'Raspberry');
INSERT INTO Légume VALUES (12, 0, 'Cos lettuce');
INSERT INTO Légume VALUES (13, 1, 'Green beans');
INSERT INTO Légume VALUES (14, 1, 'Parsnip');
INSERT INTO Légume VALUES (15, 1, 'Radish');
INSERT INTO Légume VALUES (16, 1, 'English Spinach');
INSERT INTO Légume VALUES (17, 1, 'Chilli Pepper');
INSERT INTO Légume VALUES (18, 1, 'Zucchini');
INSERT INTO Légume VALUES (19, 0, 'Dried Chinese Broccoli');
