INSERT INTO Modèle VALUES (0, 'Tristar Compacte');
INSERT INTO Modèle VALUES (1, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (2, 'Tristar Compacte');
INSERT INTO Modèle VALUES (3, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (4, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (5, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (6, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (7, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (8, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (9, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (10, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (11, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (12, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (13, 'Tristar Compacte');
INSERT INTO Modèle VALUES (14, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (15, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (16, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (17, 'Tristar Compacte');
INSERT INTO Modèle VALUES (18, 'Moulinex Principio');
INSERT INTO Modèle VALUES (19, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (20, 'Tristar Compacte');
INSERT INTO Modèle VALUES (21, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (22, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (23, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (24, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (25, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (26, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (27, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (28, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (29, 'Moulinex Principio');
INSERT INTO Modèle VALUES (30, 'Moulinex Principio');
INSERT INTO Modèle VALUES (31, 'Moulinex Principio');
INSERT INTO Modèle VALUES (32, 'Moulinex Principio');
INSERT INTO Modèle VALUES (33, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (34, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (35, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (36, 'Moulinex Principio');
INSERT INTO Modèle VALUES (37, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (38, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (39, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (40, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (41, 'Severin Gril');
INSERT INTO Modèle VALUES (42, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (43, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (44, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (45, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (46, 'Tristar Compacte');
INSERT INTO Modèle VALUES (47, 'Moulinex Principio');
INSERT INTO Modèle VALUES (48, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (49, 'Moulinex Principio');
INSERT INTO Modèle VALUES (50, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (51, 'Tristar Compacte');
INSERT INTO Modèle VALUES (52, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (53, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (54, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (55, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (56, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (57, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (58, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (59, 'Severin Gril');
INSERT INTO Modèle VALUES (60, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (61, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (62, 'Moulinex Principio');
INSERT INTO Modèle VALUES (63, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (64, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (65, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (66, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (67, 'Tristar Compacte');
INSERT INTO Modèle VALUES (68, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (69, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (70, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (71, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (72, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (73, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (74, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (75, 'Severin Gril');
INSERT INTO Modèle VALUES (76, 'Moulinex Principio');
INSERT INTO Modèle VALUES (77, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (78, 'Moulinex Principio');
INSERT INTO Modèle VALUES (79, 'Moulinex Principio');
INSERT INTO Modèle VALUES (80, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (81, 'Tristar Compacte');
INSERT INTO Modèle VALUES (82, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (83, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (84, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (85, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (86, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (87, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (88, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (89, 'Moulinex Principio');
INSERT INTO Modèle VALUES (90, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (91, 'Severin Gril');
INSERT INTO Modèle VALUES (92, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (93, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (94, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (95, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (96, 'Severin Gril');
INSERT INTO Modèle VALUES (97, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (98, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (99, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (100, 'Severin Gril');
INSERT INTO Modèle VALUES (101, 'Moulinex Principio');
INSERT INTO Modèle VALUES (102, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (103, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (104, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (105, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (106, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (107, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (108, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (109, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (110, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (111, 'Moulinex Principio');
INSERT INTO Modèle VALUES (112, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (113, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (114, 'Moulinex Principio');
INSERT INTO Modèle VALUES (115, 'Tristar Compacte');
INSERT INTO Modèle VALUES (116, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (117, 'Severin Gril');
INSERT INTO Modèle VALUES (118, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (119, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (120, 'Tefal Pierrade');
