INSERT INTO Modèle VALUES (0, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (1, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (2, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (3, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (4, 'Moulinex Principio');
INSERT INTO Modèle VALUES (5, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (6, 'Severin Gril');
INSERT INTO Modèle VALUES (7, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (8, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (9, 'Tristar Compacte');
INSERT INTO Modèle VALUES (10, 'Severin Gril');
INSERT INTO Modèle VALUES (11, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (12, 'Tristar Compacte');
INSERT INTO Modèle VALUES (13, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (14, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (15, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (16, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (17, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (18, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (19, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (20, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (21, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (22, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (23, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (24, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (25, 'Severin Gril');
INSERT INTO Modèle VALUES (26, 'Severin Gril');
INSERT INTO Modèle VALUES (27, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (28, 'Moulinex Principio');
INSERT INTO Modèle VALUES (29, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (30, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (31, 'Tristar Compacte');
INSERT INTO Modèle VALUES (32, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (33, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (34, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (35, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (36, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (37, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (38, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (39, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (40, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (41, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (42, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (43, 'Severin Gril');
INSERT INTO Modèle VALUES (44, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (45, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (46, 'Severin Gril');
INSERT INTO Modèle VALUES (47, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (48, 'Tristar Compacte');
INSERT INTO Modèle VALUES (49, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (50, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (51, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (52, 'Tristar Compacte');
INSERT INTO Modèle VALUES (53, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (54, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (55, 'Tristar Compacte');
INSERT INTO Modèle VALUES (56, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (57, 'Tristar Compacte');
INSERT INTO Modèle VALUES (58, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (59, 'Severin Gril');
INSERT INTO Modèle VALUES (60, 'Severin Gril');
INSERT INTO Modèle VALUES (61, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (62, 'Severin Gril');
INSERT INTO Modèle VALUES (63, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (64, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (65, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (66, 'Tristar Compacte');
INSERT INTO Modèle VALUES (67, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (68, 'Moulinex Principio');
INSERT INTO Modèle VALUES (69, 'Tristar Compacte');
INSERT INTO Modèle VALUES (70, 'Moulinex Principio');
INSERT INTO Modèle VALUES (71, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (72, 'Tristar Compacte');
INSERT INTO Modèle VALUES (73, 'Severin Gril');
INSERT INTO Modèle VALUES (74, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (75, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (76, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (77, 'Tristar Compacte');
INSERT INTO Modèle VALUES (78, 'Severin Gril');
INSERT INTO Modèle VALUES (79, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (80, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (81, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (82, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (83, 'Severin Gril');
INSERT INTO Modèle VALUES (84, 'Tristar Compacte');
INSERT INTO Modèle VALUES (85, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (86, 'Moulinex Principio');
INSERT INTO Modèle VALUES (87, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (88, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (89, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (90, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (91, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (92, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (93, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (94, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (95, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (96, 'Moulinex Principio');
INSERT INTO Modèle VALUES (97, 'Tristar Compacte');
INSERT INTO Modèle VALUES (98, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (99, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (100, 'Severin Gril');
INSERT INTO Modèle VALUES (101, 'Tristar Compacte');
INSERT INTO Modèle VALUES (102, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (103, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (104, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (105, 'Severin Gril');
INSERT INTO Modèle VALUES (106, 'Tristar Compacte');
INSERT INTO Modèle VALUES (107, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (108, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (109, 'Severin Gril');
INSERT INTO Modèle VALUES (110, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (111, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (112, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (113, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (114, 'Tristar Compacte');
INSERT INTO Modèle VALUES (115, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (116, 'Tristar Compacte');
INSERT INTO Modèle VALUES (117, 'Moulinex Principio');
INSERT INTO Modèle VALUES (118, 'Severin Gril');
INSERT INTO Modèle VALUES (119, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (120, 'EssentielB Multi-raclette');
