INSERT INTO Modèle VALUES (1, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (2, 'Tristar Compacte');
INSERT INTO Modèle VALUES (3, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (4, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (5, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (6, 'Severin Gril');
INSERT INTO Modèle VALUES (7, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (8, 'Moulinex Principio');
INSERT INTO Modèle VALUES (9, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (10, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (11, 'Severin Gril');
INSERT INTO Modèle VALUES (12, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (13, 'Severin Gril');
INSERT INTO Modèle VALUES (14, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (15, 'Tristar Compacte');
INSERT INTO Modèle VALUES (16, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (17, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (18, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (19, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (20, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (21, 'Tristar Compacte');
INSERT INTO Modèle VALUES (22, 'Moulinex Principio');
INSERT INTO Modèle VALUES (23, 'Tristar Compacte');
INSERT INTO Modèle VALUES (24, 'Tristar Compacte');
INSERT INTO Modèle VALUES (25, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (26, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (27, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (28, 'Severin Gril');
INSERT INTO Modèle VALUES (29, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (30, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (31, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (32, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (33, 'Tristar Compacte');
INSERT INTO Modèle VALUES (34, 'Tristar Compacte');
INSERT INTO Modèle VALUES (35, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (36, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (37, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (38, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (39, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (40, 'Moulinex Principio');
INSERT INTO Modèle VALUES (41, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (42, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (43, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (44, 'Tristar Compacte');
INSERT INTO Modèle VALUES (45, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (46, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (47, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (48, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (49, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (50, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (51, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (52, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (53, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (54, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (55, 'Severin Gril');
INSERT INTO Modèle VALUES (56, 'Moulinex Principio');
INSERT INTO Modèle VALUES (57, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (58, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (59, 'Moulinex Principio');
INSERT INTO Modèle VALUES (60, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (61, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (62, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (63, 'Moulinex Principio');
INSERT INTO Modèle VALUES (64, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (65, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (66, 'Moulinex Principio');
INSERT INTO Modèle VALUES (67, 'Severin Gril');
INSERT INTO Modèle VALUES (68, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (69, 'Moulinex Principio');
INSERT INTO Modèle VALUES (70, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (71, 'Severin Gril');
INSERT INTO Modèle VALUES (72, 'Tristar Compacte');
INSERT INTO Modèle VALUES (73, 'EssentielB Multi-raclette');
INSERT INTO Modèle VALUES (74, 'Tristar Compacte');
INSERT INTO Modèle VALUES (75, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (76, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (77, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (78, 'Tristar Compacte');
INSERT INTO Modèle VALUES (79, 'Tristar Compacte');
INSERT INTO Modèle VALUES (80, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (81, 'Moulinex Principio');
INSERT INTO Modèle VALUES (82, 'Severin Gril');
INSERT INTO Modèle VALUES (83, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (84, 'Lagrange Transparence');
INSERT INTO Modèle VALUES (85, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (86, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (87, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (88, 'Severin Gril');
INSERT INTO Modèle VALUES (89, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (90, 'Tristar Compacte');
INSERT INTO Modèle VALUES (91, 'Moulinex Principio');
INSERT INTO Modèle VALUES (92, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (93, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (94, 'Tefal 6 personnes');
INSERT INTO Modèle VALUES (95, 'Louis Tellier Brézière');
INSERT INTO Modèle VALUES (96, 'Severin Gril');
INSERT INTO Modèle VALUES (97, 'Bron Coucke Traditionnelle');
INSERT INTO Modèle VALUES (98, 'Klarstein Appenzell');
INSERT INTO Modèle VALUES (99, 'Tefal Pierrade');
INSERT INTO Modèle VALUES (100, 'Lagrange Transparence');
