INSERT INTO Organisation VALUES (1, 'Cumquat', 'Ordre', 7);
INSERT INTO Organisation VALUES (2, 'Blood oranges', 'Ordre', 8);
INSERT INTO Organisation VALUES (3, 'Blackberries', 'Ordre', 0);
INSERT INTO Organisation VALUES (4, 'Lemon', 'Ordre', 35);
INSERT INTO Organisation VALUES (5, 'Mulberries', 'Ordre', 7);
INSERT INTO Organisation VALUES (6, 'Mulberries', 'Ordre', 20);
INSERT INTO Organisation VALUES (7, 'Mangosteens', 'Ordre', 10);
INSERT INTO Organisation VALUES (8, 'Mulberries', 'Ordre', 46);
INSERT INTO Organisation VALUES (9, 'Cranberry', 'Ordre', 4);
INSERT INTO Organisation VALUES (10, 'Blackberries', 'Ordre', 41);
INSERT INTO Organisation VALUES (11, 'Elderberry', 'Club', 4);
INSERT INTO Organisation VALUES (12, 'Incaberries', 'Club', 44);
INSERT INTO Organisation VALUES (13, 'Watermelon', 'Club', 39);
INSERT INTO Organisation VALUES (14, 'Oranges', 'Club', 27);
INSERT INTO Organisation VALUES (15, 'Kiwi Fruit', 'Club', 11);
INSERT INTO Organisation VALUES (16, 'Watermelon', 'Club', 34);
INSERT INTO Organisation VALUES (17, 'Plums', 'Club', 36);
INSERT INTO Organisation VALUES (18, 'Corella Pear', 'Club', 15);
INSERT INTO Organisation VALUES (19, 'Cranberry', 'Club', 35);
INSERT INTO Organisation VALUES (20, 'Cranberry', 'Club', 1);
INSERT INTO Organisation VALUES (21, 'Dates', 'Club', 37);
INSERT INTO Organisation VALUES (22, 'Peaches', 'Club', 33);
INSERT INTO Organisation VALUES (23, 'Dried Apricots', 'Club', 43);
INSERT INTO Organisation VALUES (24, 'Juniper Berries', 'Club', 47);
INSERT INTO Organisation VALUES (25, 'Custard Apples', 'Club', 42);
INSERT INTO Organisation VALUES (26, 'Tomatoes', 'Club', 30);
INSERT INTO Organisation VALUES (27, 'Papaw', 'Club', 45);
INSERT INTO Organisation VALUES (28, 'Mangosteens', 'Club', 17);
INSERT INTO Organisation VALUES (29, 'Mango', 'Club', 32);
INSERT INTO Organisation VALUES (30, 'Nectarines', 'Club', 10);
INSERT INTO Organisation VALUES (31, 'Starfruit', 'Club', 16);
INSERT INTO Organisation VALUES (32, 'Cherries', 'Club', 22);
INSERT INTO Organisation VALUES (33, 'Prunes', 'Club', 41);
INSERT INTO Organisation VALUES (34, 'Olives', 'Club', 14);
INSERT INTO Organisation VALUES (35, 'Figs', 'Club', 50);
INSERT INTO Organisation VALUES (36, 'Custard Apples Daikon', 'Club', 42);
INSERT INTO Organisation VALUES (37, 'Goji Berry', 'Club', 0);
INSERT INTO Organisation VALUES (38, 'Passionfruit', 'Club', 45);
INSERT INTO Organisation VALUES (39, 'Dates', 'Club', 14);
INSERT INTO Organisation VALUES (40, 'Nectarines', 'Club', 48);
INSERT INTO Organisation VALUES (41, 'Nashi Pear', 'Club', 23);
INSERT INTO Organisation VALUES (42, 'Fingerlime', 'Club', 16);
INSERT INTO Organisation VALUES (43, 'Corella Pear', 'Club', 6);
INSERT INTO Organisation VALUES (44, 'Olives', 'Club', 48);
INSERT INTO Organisation VALUES (45, 'Feijoa', 'Club', 32);
INSERT INTO Organisation VALUES (46, 'Mangosteens', 'Club', 15);
INSERT INTO Organisation VALUES (47, 'Cumquat', 'Club', 38);
INSERT INTO Organisation VALUES (48, 'Feijoa', 'Club', 43);
INSERT INTO Organisation VALUES (49, 'Pomegranate', 'Club', 8);
INSERT INTO Organisation VALUES (50, 'Pomegranate', 'Club', 48);
INSERT INTO Organisation VALUES (51, 'Lychees', 'Club', 34);
INSERT INTO Organisation VALUES (52, 'Mangosteens', 'Club', 49);
INSERT INTO Organisation VALUES (53, 'Oranges', 'Club', 49);
INSERT INTO Organisation VALUES (54, 'Pomegranate', 'Club', 1);
INSERT INTO Organisation VALUES (55, 'Dragonfruit', 'Club', 45);
INSERT INTO Organisation VALUES (56, 'Juniper Berries', 'Club', 8);
INSERT INTO Organisation VALUES (57, 'Peaches', 'Club', 32);
INSERT INTO Organisation VALUES (58, 'Olives', 'Club', 1);
INSERT INTO Organisation VALUES (59, 'Blood oranges', 'Club', 9);
INSERT INTO Organisation VALUES (60, 'Feijoa', 'Club', 41);
