INSERT INTO Organisation VALUES (1, 'Juniper Berries', 'Ordre', 4);
INSERT INTO Organisation VALUES (2, 'Apples', 'Ordre', 11);
INSERT INTO Organisation VALUES (3, 'Nashi Pear', 'Ordre', 4);
INSERT INTO Organisation VALUES (4, 'Rockmelon', 'Ordre', 22);
INSERT INTO Organisation VALUES (5, 'Melon', 'Ordre', 30);
INSERT INTO Organisation VALUES (6, 'Mangosteens', 'Ordre', 32);
INSERT INTO Organisation VALUES (7, 'Watermelon', 'Ordre', 2);
INSERT INTO Organisation VALUES (8, 'Oranges', 'Ordre', 33);
INSERT INTO Organisation VALUES (9, 'Dragonfruit', 'Ordre', 35);
INSERT INTO Organisation VALUES (10, 'Currants', 'Ordre', 15);
INSERT INTO Organisation VALUES (11, 'Blueberries', 'Club', 23);
INSERT INTO Organisation VALUES (12, 'Mulberries', 'Club', 25);
INSERT INTO Organisation VALUES (13, 'Custard Apples', 'Club', 35);
INSERT INTO Organisation VALUES (14, 'Nashi Pear', 'Club', 12);
INSERT INTO Organisation VALUES (15, 'Mangosteens', 'Club', 13);
INSERT INTO Organisation VALUES (16, 'Sprouts', 'Club', 34);
INSERT INTO Organisation VALUES (17, 'Cranberry', 'Club', 39);
INSERT INTO Organisation VALUES (18, 'Cranberry', 'Club', 32);
INSERT INTO Organisation VALUES (19, 'Currants', 'Club', 38);
INSERT INTO Organisation VALUES (20, 'Cavalo', 'Club', 40);
INSERT INTO Organisation VALUES (21, 'Dragonfruit', 'Club', 22);
INSERT INTO Organisation VALUES (22, 'Bush Tomato', 'Club', 24);
INSERT INTO Organisation VALUES (23, 'Tomatoes', 'Club', 12);
INSERT INTO Organisation VALUES (24, 'Grapes', 'Club', 49);
INSERT INTO Organisation VALUES (25, 'Elderberry', 'Club', 47);
INSERT INTO Organisation VALUES (26, 'Aubergine', 'Club', 2);
INSERT INTO Organisation VALUES (27, 'Kiwiberries', 'Club', 33);
INSERT INTO Organisation VALUES (28, 'Lemon', 'Club', 48);
INSERT INTO Organisation VALUES (29, 'Sprouts', 'Club', 6);
INSERT INTO Organisation VALUES (30, 'Custard Apples Daikon', 'Club', 49);
INSERT INTO Organisation VALUES (31, 'Elderberry', 'Club', 1);
INSERT INTO Organisation VALUES (32, 'Limes', 'Club', 29);
INSERT INTO Organisation VALUES (33, 'Cumquat', 'Club', 4);
INSERT INTO Organisation VALUES (34, 'Watermelon', 'Club', 7);
INSERT INTO Organisation VALUES (35, 'Blood oranges', 'Club', 42);
INSERT INTO Organisation VALUES (36, 'Elderberry', 'Club', 3);
INSERT INTO Organisation VALUES (37, 'Longan', 'Club', 43);
INSERT INTO Organisation VALUES (38, 'Olives', 'Club', 32);
INSERT INTO Organisation VALUES (39, 'Loquats', 'Club', 9);
INSERT INTO Organisation VALUES (40, 'Strawberries', 'Club', 21);
INSERT INTO Organisation VALUES (41, 'Prunes', 'Club', 46);
INSERT INTO Organisation VALUES (42, 'Apples', 'Club', 1);
INSERT INTO Organisation VALUES (43, 'Guava', 'Club', 35);
INSERT INTO Organisation VALUES (44, 'Guava', 'Club', 7);
INSERT INTO Organisation VALUES (45, 'Honeydew melon', 'Club', 46);
INSERT INTO Organisation VALUES (46, 'Melon', 'Club', 23);
INSERT INTO Organisation VALUES (47, 'Aubergine', 'Club', 27);
INSERT INTO Organisation VALUES (48, 'Sprouts', 'Club', 2);
INSERT INTO Organisation VALUES (49, 'Banana', 'Club', 43);
INSERT INTO Organisation VALUES (50, 'Grapes', 'Club', 41);
INSERT INTO Organisation VALUES (51, 'Butternut pumpkin', 'Club', 22);
INSERT INTO Organisation VALUES (52, 'Mango', 'Club', 35);
INSERT INTO Organisation VALUES (53, 'Loquats', 'Club', 8);
INSERT INTO Organisation VALUES (54, 'Nectarines', 'Club', 50);
INSERT INTO Organisation VALUES (55, 'Cavalo', 'Club', 15);
INSERT INTO Organisation VALUES (56, 'Starfruit', 'Club', 39);
INSERT INTO Organisation VALUES (57, 'Pears', 'Club', 48);
INSERT INTO Organisation VALUES (58, 'Aubergine', 'Club', 37);
INSERT INTO Organisation VALUES (59, 'Watermelon', 'Club', 30);
INSERT INTO Organisation VALUES (60, 'Custard Apples', 'Club', 42);
