INSERT INTO Organisation VALUES (1, 'Goji Berry', 'Ordre', 64);
INSERT INTO Organisation VALUES (2, 'Snowpeas', 'Ordre', 89);
INSERT INTO Organisation VALUES (3, 'Papaw', 'Ordre', 16);
INSERT INTO Organisation VALUES (4, 'Pineapple', 'Ordre', 35);
INSERT INTO Organisation VALUES (5, 'Dragonfruit', 'Ordre', 86);
INSERT INTO Organisation VALUES (6, 'Pineapple', 'Ordre', 65);
INSERT INTO Organisation VALUES (7, 'Custard Apples', 'Ordre', 74);
INSERT INTO Organisation VALUES (8, 'Guava', 'Ordre', 33);
INSERT INTO Organisation VALUES (9, 'Honeydew melon', 'Ordre', 42);
INSERT INTO Organisation VALUES (10, 'Bush Tomato', 'Ordre', 79);
INSERT INTO Organisation VALUES (11, 'Honeydew melon', 'Club', 2);
INSERT INTO Organisation VALUES (12, 'Watermelon', 'Club', 49);
INSERT INTO Organisation VALUES (13, 'Lychees', 'Club', 76);
INSERT INTO Organisation VALUES (14, 'Sultanas', 'Club', 73);
INSERT INTO Organisation VALUES (15, 'Loquats', 'Club', 48);
INSERT INTO Organisation VALUES (16, 'Longan', 'Club', 23);
INSERT INTO Organisation VALUES (17, 'Incaberries', 'Club', 27);
INSERT INTO Organisation VALUES (18, 'Melon', 'Club', 48);
INSERT INTO Organisation VALUES (19, 'Grapefruit', 'Club', 66);
INSERT INTO Organisation VALUES (20, 'Prunes', 'Club', 4);
INSERT INTO Organisation VALUES (21, 'Loquats', 'Club', 89);
INSERT INTO Organisation VALUES (22, 'Fingerlime', 'Club', 12);
INSERT INTO Organisation VALUES (23, 'Prunes', 'Club', 1);
INSERT INTO Organisation VALUES (24, 'Feijoa', 'Club', 34);
INSERT INTO Organisation VALUES (25, 'Mangosteens', 'Club', 100);
INSERT INTO Organisation VALUES (26, 'Starfruit', 'Club', 6);
INSERT INTO Organisation VALUES (27, 'Juniper Berries', 'Club', 5);
INSERT INTO Organisation VALUES (28, 'Elderberry', 'Club', 13);
INSERT INTO Organisation VALUES (29, 'Cavalo', 'Club', 3);
INSERT INTO Organisation VALUES (30, 'Juniper Berries', 'Club', 4);
INSERT INTO Organisation VALUES (31, 'Apricots', 'Club', 58);
INSERT INTO Organisation VALUES (32, 'Blackberries', 'Club', 15);
INSERT INTO Organisation VALUES (33, 'Cranberry', 'Club', 21);
INSERT INTO Organisation VALUES (34, 'Corella Pear', 'Club', 25);
INSERT INTO Organisation VALUES (35, 'Lemon', 'Club', 21);
INSERT INTO Organisation VALUES (36, 'Avocado', 'Club', 19);
INSERT INTO Organisation VALUES (37, 'Snowpeas', 'Club', 25);
INSERT INTO Organisation VALUES (38, 'Banana', 'Club', 2);
INSERT INTO Organisation VALUES (39, 'Limes', 'Club', 51);
INSERT INTO Organisation VALUES (40, 'Loquats', 'Club', 74);
INSERT INTO Organisation VALUES (41, 'Nashi Pear', 'Club', 33);
INSERT INTO Organisation VALUES (42, 'Strawberries', 'Club', 93);
INSERT INTO Organisation VALUES (43, 'Fingerlime', 'Club', 34);
INSERT INTO Organisation VALUES (44, 'Loquats', 'Club', 3);
INSERT INTO Organisation VALUES (45, 'Nectarines', 'Club', 57);
INSERT INTO Organisation VALUES (46, 'Melon', 'Club', 15);
INSERT INTO Organisation VALUES (47, 'Plums', 'Club', 80);
INSERT INTO Organisation VALUES (48, 'Cherries', 'Club', 90);
INSERT INTO Organisation VALUES (49, 'Apricots', 'Club', 61);
INSERT INTO Organisation VALUES (50, 'Lychees', 'Club', 76);
INSERT INTO Organisation VALUES (51, 'Dragonfruit', 'Club', 20);
INSERT INTO Organisation VALUES (52, 'Guava', 'Club', 13);
INSERT INTO Organisation VALUES (53, 'Nashi Pear', 'Club', 70);
INSERT INTO Organisation VALUES (54, 'Longan', 'Club', 12);
INSERT INTO Organisation VALUES (55, 'Grapefruit', 'Club', 2);
INSERT INTO Organisation VALUES (56, 'Cantaloupe', 'Club', 65);
INSERT INTO Organisation VALUES (57, 'Mango', 'Club', 9);
INSERT INTO Organisation VALUES (58, 'Prunes', 'Club', 37);
INSERT INTO Organisation VALUES (59, 'Figs', 'Club', 76);
INSERT INTO Organisation VALUES (60, 'Loquats', 'Club', 29);
