INSERT INTO Plat VALUES (1, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (2, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (3, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (4, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (5, 3, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (6, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (7, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (8, 10, 'Crevettes sautées');
INSERT INTO Plat VALUES (9, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (10, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (11, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (12, 8, 'Crevettes sautées');
INSERT INTO Plat VALUES (13, 16, 'Poulet cacahuète');
INSERT INTO Plat VALUES (14, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (15, 8, 'Crevettes sautées');
INSERT INTO Plat VALUES (16, 15, 'Pâtes au fromage');
INSERT INTO Plat VALUES (17, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (18, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (19, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (20, 16, 'Pâtes au fromage');
INSERT INTO Plat VALUES (21, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (22, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (23, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (24, 19, 'Dahl de lentilles');
INSERT INTO Plat VALUES (25, 3, 'Dahl de lentilles');
INSERT INTO Plat VALUES (26, 13, 'Riz sauté soja');
INSERT INTO Plat VALUES (27, 8, 'Poulet au curry');
INSERT INTO Plat VALUES (28, 14, 'Dahl de lentilles');
INSERT INTO Plat VALUES (29, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (30, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (31, 4, 'Dahl de lentilles');
INSERT INTO Plat VALUES (32, 11, 'Dahl de lentilles');
INSERT INTO Plat VALUES (33, 10, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (34, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (35, 9, 'Saumon rôti');
INSERT INTO Plat VALUES (36, 11, 'Pâtes au fromage');
INSERT INTO Plat VALUES (37, 19, 'Poulet au curry');
INSERT INTO Plat VALUES (38, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (39, 18, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (40, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (41, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (42, 8, 'Riz sauté soja');
INSERT INTO Plat VALUES (43, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (44, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (45, 15, 'Crevettes sautées');
INSERT INTO Plat VALUES (46, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (47, 11, 'Poulet au curry');
INSERT INTO Plat VALUES (48, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (49, 17, 'Saumon rôti');
INSERT INTO Plat VALUES (50, 17, 'Dahl de lentilles');
INSERT INTO Plat VALUES (51, 15, 'Pâtes au saumon');
INSERT INTO Plat VALUES (52, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (53, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (54, 7, 'Omelette herbes');
INSERT INTO Plat VALUES (55, 3, 'Crevettes sautées');
INSERT INTO Plat VALUES (56, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (57, 19, 'Poulet au curry');
INSERT INTO Plat VALUES (58, 19, 'Crevettes sautées');
INSERT INTO Plat VALUES (59, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (60, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (61, 11, 'Crevettes sautées');
INSERT INTO Plat VALUES (62, 18, 'Cabillaud poché');
INSERT INTO Plat VALUES (63, 8, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (64, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (65, 19, 'Omelette herbes');
INSERT INTO Plat VALUES (66, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (67, 4, 'Cabillaud poché');
INSERT INTO Plat VALUES (68, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (69, 16, 'Cabillaud poché');
INSERT INTO Plat VALUES (70, 6, 'Pâtes au saumon');
INSERT INTO Plat VALUES (71, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (72, 9, 'Bœuf au poivre');
INSERT INTO Plat VALUES (73, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (74, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (75, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (76, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (77, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (78, 4, 'Pâtes au saumon');
INSERT INTO Plat VALUES (79, 8, 'Saumon rôti');
INSERT INTO Plat VALUES (80, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (81, 13, 'Omelette herbes');
INSERT INTO Plat VALUES (82, 5, 'Saumon rôti');
INSERT INTO Plat VALUES (83, 7, 'Omelette herbes');
INSERT INTO Plat VALUES (84, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (85, 15, 'Crevettes sautées');
INSERT INTO Plat VALUES (86, 15, 'Cabillaud poché');
INSERT INTO Plat VALUES (87, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (88, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (89, 5, 'Poulet au curry');
INSERT INTO Plat VALUES (90, 4, 'Omelette herbes');
INSERT INTO Plat VALUES (91, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (92, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (93, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (94, 6, 'Cabillaud poché');
INSERT INTO Plat VALUES (95, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (96, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (97, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (98, 15, 'Crevettes sautées');
INSERT INTO Plat VALUES (99, 17, 'Omelette herbes');
INSERT INTO Plat VALUES (100, 4, 'Poulet au curry');
INSERT INTO Plat VALUES (101, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (102, 18, 'Dahl de lentilles');
INSERT INTO Plat VALUES (103, 6, 'Omelette herbes');
INSERT INTO Plat VALUES (104, 19, 'Poulet au curry');
INSERT INTO Plat VALUES (105, 16, 'Omelette herbes');
INSERT INTO Plat VALUES (106, 7, 'Poulet cacahuète');
INSERT INTO Plat VALUES (107, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (108, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (109, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (110, 16, 'Saumon rôti');
INSERT INTO Plat VALUES (111, 12, 'Riz sauté soja');
INSERT INTO Plat VALUES (112, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (113, 5, 'Riz sauté soja');
INSERT INTO Plat VALUES (114, 1, 'Pâtes au fromage');
INSERT INTO Plat VALUES (115, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (116, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (117, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (118, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (119, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (120, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (121, 17, 'Poulet cacahuète');
INSERT INTO Plat VALUES (122, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (123, 13, 'Pâtes au fromage');
INSERT INTO Plat VALUES (124, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (125, 4, 'Pâtes au saumon');
INSERT INTO Plat VALUES (126, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (127, 3, 'Saumon rôti');
INSERT INTO Plat VALUES (128, 14, 'Pâtes au saumon');
INSERT INTO Plat VALUES (129, 11, 'Dahl de lentilles');
INSERT INTO Plat VALUES (130, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (131, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (132, 13, 'Dahl de lentilles');
INSERT INTO Plat VALUES (133, 5, 'Poulet au curry');
INSERT INTO Plat VALUES (134, 15, 'Pâtes au saumon');
INSERT INTO Plat VALUES (135, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (136, 2, 'Crevettes sautées');
INSERT INTO Plat VALUES (137, 12, 'Pâtes au fromage');
INSERT INTO Plat VALUES (138, 3, 'Pâtes au fromage');
INSERT INTO Plat VALUES (139, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (140, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (141, 7, 'Poulet cacahuète');
INSERT INTO Plat VALUES (142, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (143, 13, 'Poulet cacahuète');
INSERT INTO Plat VALUES (144, 1, 'Crevettes sautées');
INSERT INTO Plat VALUES (145, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (146, 17, 'Crevettes sautées');
INSERT INTO Plat VALUES (147, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (148, 7, 'Pâtes au saumon');
INSERT INTO Plat VALUES (149, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (150, 9, 'Dahl de lentilles');
INSERT INTO Plat VALUES (151, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (152, 16, 'Poulet cacahuète');
INSERT INTO Plat VALUES (153, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (154, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (155, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (156, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (157, 4, 'Omelette herbes');
INSERT INTO Plat VALUES (158, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (159, 18, 'Poulet cacahuète');
INSERT INTO Plat VALUES (160, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (161, 13, 'Saumon rôti');
INSERT INTO Plat VALUES (162, 17, 'Pâtes au fromage');
INSERT INTO Plat VALUES (163, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (164, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (165, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (166, 4, 'Omelette herbes');
INSERT INTO Plat VALUES (167, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (168, 5, 'Pâtes au fromage');
INSERT INTO Plat VALUES (169, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (170, 14, 'Saumon rôti');
INSERT INTO Plat VALUES (171, 15, 'Cabillaud poché');
INSERT INTO Plat VALUES (172, 10, 'Crevettes sautées');
INSERT INTO Plat VALUES (173, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (174, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (175, 3, 'Poulet au curry');
INSERT INTO Plat VALUES (176, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (177, 14, 'Crevettes sautées');
INSERT INTO Plat VALUES (178, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (179, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (180, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (181, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (182, 17, 'Omelette herbes');
INSERT INTO Plat VALUES (183, 10, 'Bœuf au poivre');
INSERT INTO Plat VALUES (184, 6, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (185, 16, 'Dahl de lentilles');
INSERT INTO Plat VALUES (186, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (187, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (188, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (189, 7, 'Cabillaud poché');
INSERT INTO Plat VALUES (190, 10, 'Crevettes sautées');
INSERT INTO Plat VALUES (191, 17, 'Saumon rôti');
INSERT INTO Plat VALUES (192, 6, 'Pâtes au saumon');
INSERT INTO Plat VALUES (193, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (194, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (195, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (196, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (197, 8, 'Omelette herbes');
INSERT INTO Plat VALUES (198, 15, 'Crevettes sautées');
INSERT INTO Plat VALUES (199, NULL, 'Dahl de lentilles');
