INSERT INTO Plat VALUES (1, 10, 'Pâtes au saumon');
INSERT INTO Plat VALUES (2, 11, 'Riz sauté soja');
INSERT INTO Plat VALUES (3, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (4, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (5, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (6, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (7, 16, 'Pâtes au fromage');
INSERT INTO Plat VALUES (8, 19, 'Poulet cacahuète');
INSERT INTO Plat VALUES (9, 17, 'Dahl de lentilles');
INSERT INTO Plat VALUES (10, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (11, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (12, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (13, 5, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (14, 7, 'Bœuf au poivre');
INSERT INTO Plat VALUES (15, 19, 'Pâtes au fromage');
INSERT INTO Plat VALUES (16, 9, 'Cabillaud poché');
INSERT INTO Plat VALUES (17, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (18, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (19, 16, 'Bœuf au poivre');
INSERT INTO Plat VALUES (20, 17, 'Cabillaud poché');
INSERT INTO Plat VALUES (21, 16, 'Dahl de lentilles');
INSERT INTO Plat VALUES (22, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (23, 9, 'Crevettes sautées');
INSERT INTO Plat VALUES (24, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (25, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (26, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (27, 3, 'Poulet au curry');
INSERT INTO Plat VALUES (28, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (29, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (30, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (31, 18, 'Pâtes au saumon');
INSERT INTO Plat VALUES (32, 6, 'Omelette herbes');
INSERT INTO Plat VALUES (33, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (34, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (35, 1, 'Cabillaud poché');
INSERT INTO Plat VALUES (36, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (37, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (38, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (39, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (40, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (41, 9, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (42, 6, 'Pâtes au saumon');
INSERT INTO Plat VALUES (43, 18, 'Riz sauté soja');
INSERT INTO Plat VALUES (44, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (45, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (46, 17, 'Poulet cacahuète');
INSERT INTO Plat VALUES (47, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (48, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (49, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (50, 19, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (51, 7, 'Crevettes sautées');
INSERT INTO Plat VALUES (52, 1, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (53, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (54, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (55, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (56, 5, 'Bœuf au poivre');
INSERT INTO Plat VALUES (57, 14, 'Riz sauté soja');
INSERT INTO Plat VALUES (58, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (59, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (60, 17, 'Pâtes au saumon');
INSERT INTO Plat VALUES (61, 14, 'Dahl de lentilles');
INSERT INTO Plat VALUES (62, 2, 'Dahl de lentilles');
INSERT INTO Plat VALUES (63, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (64, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (65, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (66, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (67, 2, 'Pâtes au fromage');
INSERT INTO Plat VALUES (68, 9, 'Bœuf au poivre');
INSERT INTO Plat VALUES (69, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (70, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (71, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (72, 6, 'Pâtes au fromage');
INSERT INTO Plat VALUES (73, 7, 'Pâtes au fromage');
INSERT INTO Plat VALUES (74, 11, 'Bœuf au poivre');
INSERT INTO Plat VALUES (75, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (76, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (77, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (78, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (79, 17, 'Omelette herbes');
INSERT INTO Plat VALUES (80, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (81, 2, 'Crevettes sautées');
INSERT INTO Plat VALUES (82, 5, 'Cabillaud poché');
INSERT INTO Plat VALUES (83, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (84, 16, 'Bœuf au poivre');
INSERT INTO Plat VALUES (85, 9, 'Saumon rôti');
INSERT INTO Plat VALUES (86, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (87, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (88, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (89, 6, 'Crevettes sautées');
INSERT INTO Plat VALUES (90, 13, 'Bœuf au poivre');
INSERT INTO Plat VALUES (91, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (92, 16, 'Bœuf au poivre');
INSERT INTO Plat VALUES (93, 18, 'Riz sauté soja');
INSERT INTO Plat VALUES (94, 14, 'Bœuf au poivre');
INSERT INTO Plat VALUES (95, 12, 'Bœuf au poivre');
INSERT INTO Plat VALUES (96, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (97, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (98, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (99, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (100, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (101, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (102, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (103, 19, 'Dahl de lentilles');
INSERT INTO Plat VALUES (104, 13, 'Crevettes sautées');
INSERT INTO Plat VALUES (105, 16, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (106, 12, 'Saumon rôti');
INSERT INTO Plat VALUES (107, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (108, 5, 'Pâtes au fromage');
INSERT INTO Plat VALUES (109, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (110, 14, 'Pâtes au fromage');
INSERT INTO Plat VALUES (111, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (112, 3, 'Pâtes au saumon');
INSERT INTO Plat VALUES (113, 6, 'Crevettes sautées');
INSERT INTO Plat VALUES (114, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (115, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (116, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (117, 19, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (118, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (119, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (120, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (121, 15, 'Riz sauté soja');
INSERT INTO Plat VALUES (122, 16, 'Cabillaud poché');
INSERT INTO Plat VALUES (123, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (124, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (125, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (126, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (127, 14, 'Saumon rôti');
INSERT INTO Plat VALUES (128, 1, 'Pâtes au saumon');
INSERT INTO Plat VALUES (129, 10, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (130, 12, 'Poulet cacahuète');
INSERT INTO Plat VALUES (131, 1, 'Cabillaud poché');
INSERT INTO Plat VALUES (132, 7, 'Pâtes au saumon');
INSERT INTO Plat VALUES (133, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (134, NULL, 'Saumon rôti');
INSERT INTO Plat VALUES (135, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (136, 2, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (137, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (138, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (139, NULL, 'Dahl de lentilles');
INSERT INTO Plat VALUES (140, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (141, 16, 'Bœuf au poivre');
INSERT INTO Plat VALUES (142, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (143, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (144, 9, 'Saumon rôti');
INSERT INTO Plat VALUES (145, 9, 'Poulet au curry');
INSERT INTO Plat VALUES (146, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (147, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (148, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (149, NULL, 'Bœuf au poivre');
INSERT INTO Plat VALUES (150, 4, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (151, 4, 'Omelette herbes');
INSERT INTO Plat VALUES (152, 5, 'Pâtes au saumon');
INSERT INTO Plat VALUES (153, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (154, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (155, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (156, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (157, 11, 'Riz sauté soja');
INSERT INTO Plat VALUES (158, NULL, 'Crevettes sautées');
INSERT INTO Plat VALUES (159, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (160, 12, 'Dahl de lentilles');
INSERT INTO Plat VALUES (161, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (162, 4, 'Pâtes au fromage');
INSERT INTO Plat VALUES (163, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (164, 6, 'Pâtes au fromage');
INSERT INTO Plat VALUES (165, 4, 'Pâtes au fromage');
INSERT INTO Plat VALUES (166, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (167, 8, 'Riz sauté soja');
INSERT INTO Plat VALUES (168, 19, 'Saumon rôti');
INSERT INTO Plat VALUES (169, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (170, 16, 'Pâtes au fromage');
INSERT INTO Plat VALUES (171, 10, 'Riz sauté soja');
INSERT INTO Plat VALUES (172, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (173, NULL, 'Omelette herbes');
INSERT INTO Plat VALUES (174, 6, 'Riz sauté soja');
INSERT INTO Plat VALUES (175, NULL, 'Pâtes au saumon');
INSERT INTO Plat VALUES (176, 17, 'Riz sauté soja');
INSERT INTO Plat VALUES (177, 19, 'Poulet cacahuète');
INSERT INTO Plat VALUES (178, 14, 'Poulet au curry');
INSERT INTO Plat VALUES (179, 12, 'Dahl de lentilles');
INSERT INTO Plat VALUES (180, NULL, 'Poulet cacahuète');
INSERT INTO Plat VALUES (181, 14, 'Pâtes au saumon');
INSERT INTO Plat VALUES (182, 3, 'Saumon rôti');
INSERT INTO Plat VALUES (183, 11, 'Saumon rôti');
INSERT INTO Plat VALUES (184, 11, 'Poulet cacahuète');
INSERT INTO Plat VALUES (185, NULL, 'Pâtes au fromage');
INSERT INTO Plat VALUES (186, 1, 'Pâtes au saumon');
INSERT INTO Plat VALUES (187, 7, 'Riz sauté soja');
INSERT INTO Plat VALUES (188, NULL, 'Cabillaud poché');
INSERT INTO Plat VALUES (189, 7, 'Pâtes au saumon');
INSERT INTO Plat VALUES (190, NULL, 'Poulet au curry');
INSERT INTO Plat VALUES (191, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (192, 13, 'Crevettes sautées');
INSERT INTO Plat VALUES (193, NULL, 'Riz sauté soja');
INSERT INTO Plat VALUES (194, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (195, 14, 'Poulet cacahuète');
INSERT INTO Plat VALUES (196, 1, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (197, NULL, 'Bœuf aux carottes');
INSERT INTO Plat VALUES (198, 17, 'Pâtes au fromage');
INSERT INTO Plat VALUES (199, NULL, 'Omelette herbes');
