INSERT INTO Territoire VALUES (0, 'Rhone-Alpes');
INSERT INTO Territoire VALUES (1, 'Haute-Normandie');
INSERT INTO Territoire VALUES (2, 'Nord-Pas-de-Calais');
INSERT INTO Territoire VALUES (3, 'Île-de-France');
INSERT INTO Territoire VALUES (4, 'Corse');
INSERT INTO Territoire VALUES (5, 'Wallis-et-Futuna');
INSERT INTO Territoire VALUES (6, 'Languedoc-Roussillon');
INSERT INTO Territoire VALUES (7, 'Province-Alpes-Côte d''Azur');
INSERT INTO Territoire VALUES (8, 'Bourgogne');
INSERT INTO Territoire VALUES (9, 'Réunion');
INSERT INTO Territoire VALUES (10, 'Centre');
INSERT INTO Territoire VALUES (11, 'Mayotte');
INSERT INTO Territoire VALUES (12, 'Lorraine');
INSERT INTO Territoire VALUES (13, 'Martinique');
INSERT INTO Territoire VALUES (14, 'Basse-Normandie');
INSERT INTO Territoire VALUES (15, 'Centre');
INSERT INTO Territoire VALUES (16, 'Midi-Pyrénées');
INSERT INTO Territoire VALUES (17, 'Guyane');
INSERT INTO Territoire VALUES (18, 'Centre');
INSERT INTO Territoire VALUES (19, 'Corse');
INSERT INTO Territoire VALUES (20, 'Nord-Pas-de-Calais');
INSERT INTO Territoire VALUES (21, 'Midi-Pyrénées');
INSERT INTO Territoire VALUES (22, 'Guadeloupe');
INSERT INTO Territoire VALUES (23, 'Polynésie française');
INSERT INTO Territoire VALUES (24, 'Franche-Comté');
INSERT INTO Territoire VALUES (25, 'Rhone-Alpes');
INSERT INTO Territoire VALUES (26, 'Midi-Pyrénées');
INSERT INTO Territoire VALUES (27, 'Mayotte');
INSERT INTO Territoire VALUES (28, 'Martinique');
INSERT INTO Territoire VALUES (29, 'Guadeloupe');
INSERT INTO Territoire VALUES (30, 'Midi-Pyrénées');
INSERT INTO Territoire VALUES (31, 'Picardie');
INSERT INTO Territoire VALUES (32, 'Réunion');
INSERT INTO Territoire VALUES (33, 'Mayotte');
INSERT INTO Territoire VALUES (34, 'Centre');
INSERT INTO Territoire VALUES (35, 'Wallis-et-Futuna');
INSERT INTO Territoire VALUES (36, 'Île-de-France');
INSERT INTO Territoire VALUES (37, 'Haute-Normandie');
INSERT INTO Territoire VALUES (38, 'Midi-Pyrénées');
INSERT INTO Territoire VALUES (39, 'Province-Alpes-Côte d''Azur');
INSERT INTO Territoire VALUES (40, 'Polynésie française');
INSERT INTO Territoire VALUES (41, 'Polynésie française');
INSERT INTO Territoire VALUES (42, 'Bourgogne');
INSERT INTO Territoire VALUES (43, 'Lorraine');
INSERT INTO Territoire VALUES (44, 'Aquitaine');
INSERT INTO Territoire VALUES (45, 'Bretagne');
INSERT INTO Territoire VALUES (46, 'Saint-Pierre-et-Miquelon');
INSERT INTO Territoire VALUES (47, 'Rhone-Alpes');
INSERT INTO Territoire VALUES (48, 'Guyane');
INSERT INTO Territoire VALUES (49, 'Polynésie française');
INSERT INTO Territoire VALUES (50, 'Saint-Barthélémy');
